title: "Udacity DAND Projects"
email: "jason@jason-carter.net"
description: "Nothing to see here, just prettying up my code a bit"
baseurl: ""
url: "https://jasoncarter80.github.io/DAND/"
twitter_username: TampaDBA
github_username:  JasonCarter80
theme: jekyll-theme-architect
