title: "Udacity DAND Projects"
email: "jason@jason-carter.net"
description: "Nothing to see here, just prettying up my code a bit"
baseurl: "/DAND/"
url: "https://jasoncarter80.github.io"
twitter_username: TampaDBA
github_username:  JasonCarter80

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
